# Generated by Django 2.1.7 on 2019-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_files',
            field=models.FileField(blank=True, upload_to='post_files/'),
        ),
    ]
