# Generated by Django 2.1.7 on 2019-03-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_mainsite', '0002_post_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
